"""ORACLE — capability acceptance for adopt-rank-bm25-local-search-v1.

Reference-calibrated like the v3 chunking oracle: the authoritative
per-query rankings in ``fixtures/reference_rankings.json`` were
generated by the trusted harness from the PINNED rank_bm25 inside the
pinned container (tokenization S1, rounding S2, tie-break S3).
Runtime-held-out from the agent (oracle is never mounted into agent
containers).

Contract rules under test: S1 lower+whitespace tokenization; S2 scores
rounded to 6 decimals; S3 ties by (score desc, chunk_id asc); S4 empty
query -> zero hits; S5 top_k truncation after full ordering.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from rag_search import SEARCH_HIT_FIELDS, SearchError, search_documents

FIXDIR = Path(__file__).parent / "fixtures"
PUBLIC = FIXDIR / "public_documents.json"
HELD_OUT = FIXDIR / "held_out_documents.json"
REFERENCE = json.loads((FIXDIR / "reference_rankings.json").read_text(encoding="utf-8"))["fixtures"]

FIXTURES = (PUBLIC, HELD_OUT)
IDS = ["public", "held"]


def _payload(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _request(path: Path) -> dict:
    return _payload(path)


def _hits_by_query(response: dict) -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = {}
    for hit in response["hits"]:
        out.setdefault(hit.get("query_id", "?"), []).append(hit)
    for hits in out.values():
        hits.sort(key=lambda h: h.get("rank", 0))
    return out


@pytest.mark.parametrize("fixture", FIXTURES, ids=IDS)
def test_rankings_match_pinned_reference(fixture: Path) -> None:
    """Core check: per query, (chunk_id order, rounded score) must
    equal the pinned-reference ranking truncated to top_k (S1/S2/S3/S5)."""
    request = _request(fixture)
    by_q = _hits_by_query(search_documents(request))
    ref = REFERENCE[fixture.name]
    for q in request["queries"]:
        qid, k = q["query_id"], q["top_k"]
        want = [(p["chunk_id"], p["score"]) for p in ref[qid][:k]]
        got = [(h["chunk_id"], h["score"]) for h in by_q.get(qid, [])]
        assert got == want, f"{qid}: got {got[:4]} want {want[:4]}"


@pytest.mark.parametrize("fixture", FIXTURES, ids=IDS)
def test_hit_schema_exact_fields(fixture: Path) -> None:
    response = search_documents(_request(fixture))
    assert response["hits"], "no hits at all"
    for hit in response["hits"]:
        assert set(hit.keys()) == set(SEARCH_HIT_FIELDS)


@pytest.mark.parametrize("fixture", FIXTURES, ids=IDS)
def test_rank_contiguous_and_query_order(fixture: Path) -> None:
    request = _request(fixture)
    response = search_documents(request)
    order = [q["query_id"] for q in request["queries"]]
    seen: list[str] = []
    ranks: dict[str, list[int]] = {}
    for hit in response["hits"]:
        if hit["query_id"] not in seen:
            seen.append(hit["query_id"])
        ranks.setdefault(hit["query_id"], []).append(hit["rank"])
    assert seen == [q for q in order if ranks.get(q)]
    for qid, seq in ranks.items():
        assert seq == list(range(len(seq))), f"{qid}: ranks not contiguous from 0"


@pytest.mark.parametrize("fixture", FIXTURES, ids=IDS)
def test_hit_text_matches_corpus(fixture: Path) -> None:
    request = _request(fixture)
    texts = {d["chunk_id"]: d["text"] for d in request["documents"]}
    for hit in search_documents(request)["hits"]:
        assert hit["text"] == texts[hit["chunk_id"]]


def test_deterministic_repeat_and_input_not_mutated() -> None:
    request = _request(PUBLIC)
    snapshot = copy.deepcopy(request)
    first = search_documents(request)
    second = search_documents(_request(PUBLIC))
    assert first == second
    assert request == snapshot


def test_empty_query_yields_zero_hits() -> None:
    request = _request(PUBLIC)
    request["queries"] = [{"query_id": "q-empty", "text": "   ", "top_k": 3}]
    assert search_documents(request)["hits"] == []


def test_top_k_larger_than_corpus_truncates_cleanly() -> None:
    request = _request(PUBLIC)
    request["queries"] = [{"query_id": "q-big", "text": "offline retrieval", "top_k": 999}]
    hits = search_documents(request)["hits"]
    assert len(hits) == len(request["documents"])


def test_malformed_query_wrapped() -> None:
    request = _request(PUBLIC)
    request["queries"] = [{"query_id": "q-bad", "text": None, "top_k": 3}]
    with pytest.raises(SearchError):
        search_documents(request)
