"""ORACLE — capability acceptance for adopt-chonkie-local-chunking-v3.

Read-only, hash-guarded, runtime-held-out from the agent (agent-profile
containers do not mount /oracle; the held-out fixture set additionally
never ships to the agent workspace).

v3 is REFERENCE-CALIBRATED: the authoritative partitions in
``fixtures/reference_partitions.json`` were generated by the trusted
harness from the PINNED Chonkie wheel inside the pinned container.
Adapter output may translate ids/schema/metadata into the host
contract, but core chunk text/order/boundaries MUST equal the Chonkie
reference for the requested strategy.

Contract post-processing rules (frozen, deterministic):
  R1  whitespace-only documents yield ZERO records regardless of raw
      upstream output (recursive natively emits one whitespace chunk);
  R2  an indivisible sentence longer than chunk_size is preserved
      verbatim (sentence strategy may legitimately exceed chunk_size;
      no re-splitting) — enforced here as exact boundary equality plus
      units == char span; there is deliberately NO naive <=chunk_size
      assertion in v3.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from rag_consumer import CHUNK_RECORD_FIELDS, ConsumerChunkingError, chunk_documents

FIXDIR = Path(__file__).parent / "fixtures"
PUBLIC = FIXDIR / "public_documents.json"
HELD_OUT = FIXDIR / "held_out_documents.json"
REFERENCE = json.loads((FIXDIR / "reference_partitions.json").read_text(encoding="utf-8"))
STRATEGIES = ("sentence", "recursive")
CHUNK_SIZE = REFERENCE["chunk_size"]


def _docs(path: Path) -> list[dict]:
    return json.loads(path.read_text(encoding="utf-8"))["documents"]


def _blank(doc: dict) -> bool:
    return doc["text"].strip() == ""


def _request(path: Path, strategy: str) -> dict:
    return {"documents": _docs(path), "strategy": strategy, "chunk_size": CHUNK_SIZE}


def _reference_for(path: Path, doc_id: str, strategy: str) -> list[dict]:
    return REFERENCE["fixtures"][path.name][doc_id][strategy]


def _records_by_doc(response: dict) -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = {}
    for rec in response["records"]:
        out.setdefault(rec.get("document_id", "?"), []).append(rec)
    for recs in out.values():
        recs.sort(key=lambda r: r.get("ordinal", 0))
    return out


PARAMS = [(f, s) for f in (PUBLIC, HELD_OUT) for s in STRATEGIES]
IDS = [f"{p.name.split('_')[0]}-{s}" for p, s in PARAMS]


@pytest.mark.parametrize(("fixture", "strategy"), PARAMS, ids=IDS)
def test_boundaries_match_chonkie_reference(fixture: Path, strategy: str) -> None:
    """The core v3 check: per document, adapter chunk (start, end, text)
    sequences must EXACTLY equal the pinned-Chonkie reference for the
    requested strategy (R1: blank docs → zero records)."""
    request = _request(fixture, strategy)
    by_doc = _records_by_doc(chunk_documents(request))
    for doc in request["documents"]:
        doc_id = doc["document_id"]
        got = [(r["char_start"], r["char_end"], r["text"]) for r in by_doc.get(doc_id, [])]
        if _blank(doc):
            assert got == [], f"{doc_id}: R1 requires zero records for whitespace-only docs"
            continue
        want = [(c["start"], c["end"], c["text"]) for c in _reference_for(fixture, doc_id, strategy)]
        assert got == want, (
            f"{doc_id}/{strategy}: boundaries differ from Chonkie reference "
            f"(got {len(got)} chunk(s) {[(g[0], g[1]) for g in got][:4]}, "
            f"want {len(want)} {[(w[0], w[1]) for w in want][:4]})"
        )


@pytest.mark.parametrize(("fixture", "strategy"), PARAMS, ids=IDS)
def test_units_equal_char_span(fixture: Path, strategy: str) -> None:
    """R2: units == char_end - char_start always — including reference
    chunks that legitimately exceed chunk_size (indivisible run-ons)."""
    response = chunk_documents(_request(fixture, strategy))
    assert response["records"], "no records at all"
    for rec in response["records"]:
        assert rec["units"] == rec["char_end"] - rec["char_start"]


@pytest.mark.parametrize(("fixture", "strategy"), PARAMS, ids=IDS)
def test_record_schema_exact_fields(fixture: Path, strategy: str) -> None:
    response = chunk_documents(_request(fixture, strategy))
    for rec in response["records"]:
        assert set(rec.keys()) == set(CHUNK_RECORD_FIELDS)


@pytest.mark.parametrize(("fixture", "strategy"), PARAMS, ids=IDS)
def test_document_order_and_contiguous_ordinals(fixture: Path, strategy: str) -> None:
    request = _request(fixture, strategy)
    response = chunk_documents(request)
    non_blank_order = [d["document_id"] for d in request["documents"] if not _blank(d)]
    seen: list[str] = []
    ordinals: dict[str, list[int]] = {}
    for rec in response["records"]:
        if rec["document_id"] not in seen:
            seen.append(rec["document_id"])
        ordinals.setdefault(rec["document_id"], []).append(rec["ordinal"])
    assert seen == non_blank_order
    for doc_id, seq in ordinals.items():
        assert seq == list(range(len(seq))), f"{doc_id}: ordinals not contiguous from 0"


@pytest.mark.parametrize(("fixture", "strategy"), PARAMS, ids=IDS)
def test_ids_stable_unique_and_not_upstream(fixture: Path, strategy: str) -> None:
    first = chunk_documents(_request(fixture, strategy))
    second = chunk_documents(_request(fixture, strategy))
    ids1 = [r.get("chunk_id") for r in first["records"]]
    assert all(ids1), "records carry no chunk_id"
    assert ids1 == [r.get("chunk_id") for r in second["records"]], "ids changed between identical runs"
    assert len(ids1) == len(set(ids1)), "chunk ids not unique"
    assert not [i for i in ids1 if isinstance(i, str) and i.startswith("chnk_")], "upstream per-call ids leaked"


@pytest.mark.parametrize(("fixture", "strategy"), PARAMS, ids=IDS)
def test_metadata_passthrough(fixture: Path, strategy: str) -> None:
    request = _request(fixture, strategy)
    meta = {d["document_id"]: d["metadata"] for d in request["documents"]}
    for rec in chunk_documents(request)["records"]:
        assert rec["metadata"] == meta[rec["document_id"]]


@pytest.mark.parametrize("strategy", STRATEGIES)
def test_repeated_text_every_occurrence_covered(strategy: str) -> None:
    """Reference partitions cover the full text, so every occurrence of
    the repeated marker must fall inside exactly one record whose slice
    contains it at the right offset."""
    fixture = PUBLIC
    marker = "本方案支持完全离线运行。"
    request = _request(fixture, strategy)
    doc = next(d for d in request["documents"] if d["document_id"] == "doc-101-ops-manual")
    by_doc = _records_by_doc(chunk_documents(request))
    recs = by_doc.get("doc-101-ops-manual", [])
    occurrences = []
    at = doc["text"].find(marker)
    while at != -1:
        occurrences.append(at)
        at = doc["text"].find(marker, at + 1)
    assert len(occurrences) >= 3
    for pos in occurrences:
        end = pos + len(marker)
        overlapping = sorted(
            (r for r in recs if r["char_start"] < end and pos < r["char_end"]),
            key=lambda r: r["char_start"],
        )
        assert overlapping, f"occurrence at {pos} covered by no record"
        piece = "".join(
            r["text"][max(pos, r["char_start"]) - r["char_start"] : min(end, r["char_end"]) - r["char_start"]]
            for r in overlapping
        )
        assert piece == marker, (
            f"occurrence at {pos} not reconstructible from covering records "
            f"(partition may split it; concatenation must still equal the marker)"
        )


@pytest.mark.parametrize("strategy", STRATEGIES)
def test_input_not_mutated(strategy: str) -> None:
    request = _request(PUBLIC, strategy)
    snapshot = copy.deepcopy(request)
    chunk_documents(request)
    assert request == snapshot


@pytest.mark.parametrize("strategy", STRATEGIES)
def test_response_json_serializable(strategy: str) -> None:
    json.dumps(chunk_documents(_request(PUBLIC, strategy)), ensure_ascii=False)


@pytest.mark.parametrize("strategy", STRATEGIES)
def test_upstream_errors_wrapped(strategy: str) -> None:
    with pytest.raises(ConsumerChunkingError):
        chunk_documents(
            {
                "documents": [{"document_id": "doc-bad", "text": None, "metadata": {}}],
                "strategy": strategy,
                "chunk_size": CHUNK_SIZE,
            }
        )


def test_strategies_differ_on_run_on_document() -> None:
    """The strategy-sensitive fixture: sentence keeps the indivisible
    run-on whole (R2), recursive splits it — the adapter must reflect
    the requested strategy, not silently reuse one chunker."""
    sent = _records_by_doc(chunk_documents(_request(PUBLIC, "sentence")))["doc-104-run-on-zh"]
    rec = _records_by_doc(chunk_documents(_request(PUBLIC, "recursive")))["doc-104-run-on-zh"]
    assert [(r["char_start"], r["char_end"]) for r in sent] != [(r["char_start"], r["char_end"]) for r in rec]
    assert len(sent) == 1 and sent[0]["units"] > CHUNK_SIZE  # R2 in action
    assert len(rec) >= 2 and all(r["units"] <= CHUNK_SIZE for r in rec)
