"""ORACLE — capability acceptance for adopt-frontmatter-local-ingest-v1.

Reference-calibrated: fixtures/reference_records.json was generated by
the trusted harness from the PINNED python-frontmatter v1.3.0 inside
the pinned container, under projection P1 (date/datetime -> ISO
strings; JSON-type whitelist; recursive). Runtime-held-out from the
agent. Rules: P1 projection; P2 has_frontmatter == (metadata != {});
P3 malformed/unfenced input follows the pinned upstream's real
behaviour (recorded in the reference); P4 malformed REQUEST entries
(non-string text) wrap as rag_ingest.IngestError.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from rag_ingest import INGEST_RECORD_FIELDS, IngestError, ingest_documents

FIXDIR = Path(__file__).parent / "fixtures"
PUBLIC = FIXDIR / "public_documents.json"
HELD_OUT = FIXDIR / "held_out_documents.json"
REFERENCE = json.loads((FIXDIR / "reference_records.json").read_text(encoding="utf-8"))["fixtures"]

FIXTURES = (PUBLIC, HELD_OUT)
IDS = ["public", "held"]


def _request(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _by_doc(response: dict) -> dict[str, dict]:
    return {r.get("doc_id", "?"): r for r in response["records"]}


@pytest.mark.parametrize("fixture", FIXTURES, ids=IDS)
def test_records_match_pinned_reference(fixture: Path) -> None:
    """Core: per document, (has_frontmatter, metadata, content) must
    equal the pinned-upstream reference under projection P1."""
    request = _request(fixture)
    by_doc = _by_doc(ingest_documents(request))
    ref = REFERENCE[fixture.name]
    for doc in request["documents"]:
        did = doc["doc_id"]
        assert did in by_doc, f"no record for {did}"
        got = by_doc[did]
        want = ref[did]
        assert got["has_frontmatter"] == want["has_frontmatter"], did
        assert got["metadata"] == want["metadata"], f"{did}: metadata differs"
        assert got["content"] == want["content"], f"{did}: content differs"


@pytest.mark.parametrize("fixture", FIXTURES, ids=IDS)
def test_record_schema_exact_fields(fixture: Path) -> None:
    for rec in ingest_documents(_request(fixture))["records"]:
        assert set(rec.keys()) == set(INGEST_RECORD_FIELDS)


@pytest.mark.parametrize("fixture", FIXTURES, ids=IDS)
def test_document_order_preserved(fixture: Path) -> None:
    request = _request(fixture)
    got = [r["doc_id"] for r in ingest_documents(request)["records"]]
    assert got == [d["doc_id"] for d in request["documents"]]


@pytest.mark.parametrize("fixture", FIXTURES, ids=IDS)
def test_response_json_serializable(fixture: Path) -> None:
    json.dumps(ingest_documents(_request(fixture)), ensure_ascii=False)


def test_deterministic_repeat_and_input_not_mutated() -> None:
    request = _request(PUBLIC)
    snapshot = copy.deepcopy(request)
    assert ingest_documents(request) == ingest_documents(_request(PUBLIC))
    assert request == snapshot


def test_unfenced_document_follows_upstream_behaviour() -> None:
    """P3: the unclosed-fence sample behaves exactly as the pinned
    upstream does (reference-recorded), not as anyone's guess."""
    by_doc = _by_doc(ingest_documents(_request(PUBLIC)))
    want = REFERENCE["public_documents.json"]["d-005-malformed-unclosed"]
    got = by_doc["d-005-malformed-unclosed"]
    assert (got["has_frontmatter"], got["metadata"], got["content"]) == (
        want["has_frontmatter"], want["metadata"], want["content"],
    )


def test_malformed_request_wrapped() -> None:
    request = _request(PUBLIC)
    request["documents"] = [{"doc_id": "d-bad", "text": None}]
    with pytest.raises(IngestError):
        ingest_documents(request)
